### ISSUE TITLE
fix phpunit errors

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#28]

**Comment by haakym** [comment]
On running `phpunit` I get the following test failing:

```
1) ActivityControllerTest::testOverview                                             
A request to [http://localhost/backend/activity] failed. Received status code [500].
```

Which is due to the `$option` variable that is not set here: https://github.com/Tjoosten/website/blob/master/resources/views/layouts/back-end.blade.php#L139

`$option` is set here: https://github.com/Tjoosten/website/blob/master/app/Providers/AppServiceProvider.php#L39

I guess it defaults to null if there is no data in the `rent_status` table?

The test seems it is failing because there are no `RentStatus` option values in the test setup or for the individual test. To solve this issue I took some of the code from `RentStatus` seeder to `tests/TestCase.php` setup for the test to work with. See my pull request here: https://github.com/Tjoosten/website/pull/44

Second failing test is:

```
1) MailingTest::testMailingInsertWithoutError  
Failed asserting that 500 matches expected 302.
```

Tried this in the browser and got:

```
Swift_TransportException in AbstractSmtpTransport.php line 383:
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required"
in AbstractSmtpTransport.php line 383
at Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.1 Authentication required ', array('250')) in AbstractSmtpTransport.php line 281
at Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<contact@st-joris-turnhout.be> ', array('250'), array()) in EsmtpTransport.php line 270
```

I assume this is happening because it's trying to send an email for which it is not authenticated (in terms of mail) and perhaps if I'd have the correct info in my `.env` file this would have perhaps gone through. If this is the case, then how can we abstract the mail auth for testing so this test will pass?
