### ISSUE TITLE
Improve testing coverage.

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#48]
testing coverage is to low. We need to improve this

**Comment by ademola-raimi** [comment]
I will be fixing this. You already have 42% I guess, let's see if I can make it get to 60%

**Comment by devdrops** [comment]
@Tjoosten do you have any idea of what would be the best coverage ATM? 50%, 60%, 100%?

**Comment by Tjoosten** [comment]
much as possible?

**Comment by ademola-raimi** [comment]
70% seems great but I noticed that some of your implementations are not yet working and because of that, I would not be able to test most of it. Make sure all your implementations are working and raise an issue. Nevertheless, I would write for ones that are working and you can merge when I raise the PR.
